DROP TABLE IF EXISTS TRACK;
DROP TABLE IF EXISTS ALBUM;
DROP TABLE IF EXISTS SINGER;

CREATE TABLE SINGER (
       ID INT NOT NULL AUTO_INCREMENT
     , FIRST_NAME VARCHAR(255) NOT NULL
     , LAST_NAME VARCHAR(255) NOT NULL
     , BIRTH_DATE DATE
     , UNIQUE UQ_SINGER_1 (FIRST_NAME, LAST_NAME)
     , PRIMARY KEY (ID)
);

CREATE TABLE ALBUM (
       ID INT NOT NULL AUTO_INCREMENT
     , SINGER_ID INT NOT NULL
     , TITLE VARCHAR(255) NOT NULL
     , RELEASE_DATE DATE
     , UNIQUE UQ_SINGER_ALBUM_1 (SINGER_ID, TITLE)
     , PRIMARY KEY (ID)
     , CONSTRAINT FK_ALBUM FOREIGN KEY (SINGER_ID) REFERENCES SINGER (ID)
);

CREATE TABLE TRACK (
       TITLE VARCHAR (255) NOT NULL
     , ALBUM_ID INT NOT NULL
     , TRACK_ID INT NOT NULL
     , DURATION INT NOT NULL
     , UNIQUE UQ_ALBUM_TRACK_1 (ALBUM_ID, TRACK_ID)
     , PRIMARY KEY (TITLE)
     , CONSTRAINT FK_TRACK FOREIGN KEY (ALBUM_ID) REFERENCES ALBUM (ID)
);
