INSERT INTO SINGER (FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES ('John', 'Mayer', '1977-10-16');
INSERT INTO SINGER (FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES ('Eric', 'Clapton', '1945-03-30');
INSERT INTO SINGER (FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES ('John', 'Butler', '1975-04-01');

INSERT INTO ALBUM (SINGER_ID, TITLE, RELEASE_DATE) VALUES (1, 'The Search For Everything', '2017-01-20');
INSERT INTO ALBUM (SINGER_ID, TITLE, RELEASE_DATE) VALUES (1, 'Battle Studies', '2009-11-17');
INSERT INTO ALBUM (SINGER_ID, TITLE, RELEASE_DATE) VALUES (2, 'From The Cradle', '1994-09-13');
INSERT INTO ALBUM (SINGER_ID, TITLE, RELEASE_DATE) VALUES (2, 'Pilgrim', '1998-03-10');
INSERT INTO ALBUM (SINGER_ID, TITLE, RELEASE_DATE) VALUES (2, 'Reptile', '201-03-13');
INSERT INTO ALBUM (SINGER_ID, TITLE, RELEASE_DATE) VALUES (3, ' From The Cradle ', '1994-09-13');

INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Jacksonville', 1, 1, 197);
INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Jamajka songs', 1, 2, 214);
INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Alphabet', 1, 3, 321);
INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Rookie Man', 1, 4, 234);
INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Many Years', 1, 5, 343);

INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Christmas', 2, 1, 178);
INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Autumn song', 2, 2, 123);
INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Summer song', 2, 3, 324);
INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Helicopter Flies', 2, 4, 438);
INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Come back home', 2, 5, 343);

INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Blues Before Sunrise', 3, 1, 178);
INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Third Degree', 3, 2, 307);
INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Reconsider Baby', 3, 3, 200);
INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Hoochie Coochie Man', 3, 4, 196);
INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Five Long Years', 3, 5, 287);

INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('My Fathers Eyes', 4, 1, 178);
INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('River of Tears', 4, 2, 145);
INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Pilgrim', 4, 3, 376);
INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Broken Hearted', 4, 4, 223);
INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('One Chance', 4, 5, 198);

INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Modern Girl', 5, 1, 433);
INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Got You on My Mind', 5, 2, 232);
INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Broken Down', 5, 3, 322);
INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Find Myself', 5, 4, 412);
INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Second Nature', 5, 5, 165);

INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Losing Hand', 6, 1, 433);
INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Refreshing All', 6, 2, 232);
INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Jumping Up', 6, 3, 322);
INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Remastered Song', 6, 4, 412);
INSERT INTO TRACK (TITLE, ALBUM_ID, TRACK_ID, DURATION) VALUES ('Jump Outside', 6, 5, 165);

