DELIMITER $$
SHOW PROCEDURE STATUS WHERE DB = 'jspdb';
DROP PROCEDURE IF EXISTS SHOW_ALL_DATA;
DROP PROCEDURE IF EXISTS SHOW_COUNTED_DATA;
DROP PROCEDURE IF EXISTS SHOW_COUNTED_DATA_FOR_SINGER;
DROP PROCEDURE IF EXISTS INSERT_SINGER;
DROP PROCEDURE IF EXISTS DELETE_SINGER;
DROP PROCEDURE IF EXISTS SHOW_ALL_SINGERS;
DROP PROCEDURE IF EXISTS INSERT_ALBUM;
DROP PROCEDURE IF EXISTS DELETE_ALBUM;
DROP PROCEDURE IF EXISTS SHOW_ALL_ALBUMS;
DROP PROCEDURE IF EXISTS INSERT_TRACK;
DROP PROCEDURE IF EXISTS DELETE_TRACK;
DROP PROCEDURE IF EXISTS SHOW_ALL_TRACKS; $$